apiVersion: apps/v1
kind: Deployment
metadata:
  name: obi
  namespace: app
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: tab
  template:
    metadata:
      labels:
        app: tab
    spec:
      containers:
      - name: con1
        image: abcdata/test:''
        ports:
        - containerPort: 5000  # Application listens on port 80
