apiVersion: v1
kind: Service
metadata:
  name: obi-service
spec:
  selector:
    app: tab
  ports:
    - protocol: TCP
      port: 80        # Port on the service
      targetPort: 5000 # Port on the pod
  type: LoadBalancer
